key_colors:
  left_black: 4294867712
  left_white: 4294867712
  right_black: 4289177750
  right_white: 4288849041
key_contours:
- - - - 163
      - 151
  - - - 163
      - 195
  - - - 162
      - 196
  - - - 162
      - 198
  - - - 161
      - 199
  - - - 161
      - 222
  - - - 171
      - 222
  - - - 171
      - 199
  - - - 168
      - 199
  - - - 167
      - 198
  - - - 167
      - 151
- - - - 169
      - 152
  - - - 169
      - 197
  - - - 174
      - 197
  - - - 174
      - 196
  - - - 175
      - 195
  - - - 175
      - 152
- - - - 177
      - 151
  - - - 177
      - 196
  - - - 176
      - 197
  - - - 176
      - 198
  - - - 175
      - 199
  - - - 173
      - 199
  - - - 173
      - 222
  - - - 183
      - 222
  - - - 183
      - 199
  - - - 182
      - 199
  - - - 181
      - 198
  - - - 181
      - 151
- - - - 183
      - 152
  - - - 183
      - 197
  - - - 189
      - 197
  - - - 189
      - 152
- - - - 191
      - 151
  - - - 191
      - 198
  - - - 190
      - 199
  - - - 185
      - 199
  - - - 185
      - 222
  - - - 195
      - 222
  - - - 195
      - 151
- - - - 197
      - 151
  - - - 197
      - 222
  - - - 208
      - 222
  - - - 208
      - 199
  - - - 204
      - 199
  - - - 203
      - 198
  - - - 203
      - 151
- - - - 205
      - 152
  - - - 205
      - 197
  - - - 210
      - 197
  - - - 210
      - 195
  - - - 211
      - 194
  - - - 211
      - 152
- - - - 213
      - 151
  - - - 213
      - 195
  - - - 212
      - 196
  - - - 212
      - 198
  - - - 211
      - 199
  - - - 210
      - 199
  - - - 210
      - 222
  - - - 220
      - 222
  - - - 220
      - 199
  - - - 218
      - 199
  - - - 217
      - 198
  - - - 217
      - 151
- - - - 219
      - 152
  - - - 219
      - 197
  - - - 225
      - 197
  - - - 225
      - 152
- - - - 227
      - 151
  - - - 227
      - 198
  - - - 226
      - 199
  - - - 222
      - 199
  - - - 222
      - 222
  - - - 232
      - 222
  - - - 232
      - 151
- - - - 234
      - 151
  - - - 234
      - 222
  - - - 245
      - 222
  - - - 245
      - 200
  - - - 244
      - 199
  - - - 240
      - 199
  - - - 239
      - 198
  - - - 239
      - 151
- - - - 241
      - 152
  - - - 241
      - 197
  - - - 246
      - 197
  - - - 246
      - 196
  - - - 247
      - 195
  - - - 247
      - 152
- - - - 249
      - 151
  - - - 249
      - 196
  - - - 248
      - 197
  - - - 248
      - 198
  - - - 247
      - 199
  - - - 247
      - 222
  - - - 257
      - 222
  - - - 257
      - 199
  - - - 254
      - 199
  - - - 253
      - 198
  - - - 253
      - 151
- - - - 255
      - 152
  - - - 255
      - 197
  - - - 260
      - 197
  - - - 261
      - 196
  - - - 261
      - 152
- - - - 263
      - 151
  - - - 263
      - 197
  - - - 261
      - 199
  - - - 259
      - 199
  - - - 259
      - 222
  - - - 269
      - 222
  - - - 269
      - 199
  - - - 268
      - 199
  - - - 267
      - 198
  - - - 267
      - 151
- - - - 269
      - 152
  - - - 269
      - 197
  - - - 275
      - 197
  - - - 275
      - 152
- - - - 277
      - 151
  - - - 277
      - 191
  - - - 278
      - 192
  - - - 277
      - 193
  - - - 277
      - 198
  - - - 276
      - 199
  - - - 271
      - 199
  - - - 271
      - 222
  - - - 281
      - 222
  - - - 281
      - 151
- - - - 284
      - 151
  - - - 284
      - 222
  - - - 294
      - 222
  - - - 294
      - 199
  - - - 290
      - 199
  - - - 289
      - 198
  - - - 289
      - 151
- - - - 291
      - 152
  - - - 291
      - 197
  - - - 296
      - 197
  - - - 297
      - 196
  - - - 297
      - 152
- - - - 299
      - 151
  - - - 299
      - 197
  - - - 297
      - 199
  - - - 296
      - 199
  - - - 296
      - 222
  - - - 306
      - 222
  - - - 306
      - 199
  - - - 305
      - 199
  - - - 303
      - 197
  - - - 303
      - 151
- - - - 305
      - 152
  - - - 305
      - 196
  - - - 306
      - 197
  - - - 311
      - 197
  - - - 311
      - 193
  - - - 312
      - 192
  - - - 312
      - 184
  - - - 311
      - 183
  - - - 311
      - 152
- - - - 313
      - 151
  - - - 313
      - 182
  - - - 314
      - 183
  - - - 314
      - 193
  - - - 313
      - 194
  - - - 313
      - 198
  - - - 312
      - 199
  - - - 308
      - 199
  - - - 308
      - 222
  - - - 318
      - 222
  - - - 318
      - 151
- - - - 320
      - 151
  - - - 320
      - 222
  - - - 331
      - 222
  - - - 331
      - 199
  - - - 326
      - 199
  - - - 325
      - 198
  - - - 325
      - 151
- - - - 327
      - 152
  - - - 327
      - 197
  - - - 332
      - 197
  - - - 333
      - 196
  - - - 333
      - 152
- - - - 335
      - 151
  - - - 335
      - 197
  - - - 333
      - 199
  - - - 333
      - 222
  - - - 343
      - 222
  - - - 343
      - 199
  - - - 340
      - 199
  - - - 339
      - 198
  - - - 339
      - 151
- - - - 341
      - 152
  - - - 341
      - 197
  - - - 347
      - 197
  - - - 347
      - 152
- - - - 349
      - 151
  - - - 349
      - 198
  - - - 348
      - 199
  - - - 345
      - 199
  - - - 345
      - 222
  - - - 355
      - 222
  - - - 355
      - 199
  - - - 353
      - 197
  - - - 353
      - 151
- - - - 355
      - 152
  - - - 355
      - 196
  - - - 356
      - 197
  - - - 361
      - 197
  - - - 361
      - 193
  - - - 362
      - 192
  - - - 362
      - 183
  - - - 361
      - 182
  - - - 361
      - 152
- - - - 363
      - 151
  - - - 363
      - 181
  - - - 364
      - 182
  - - - 364
      - 193
  - - - 363
      - 194
  - - - 363
      - 198
  - - - 362
      - 199
  - - - 357
      - 199
  - - - 357
      - 222
  - - - 368
      - 222
  - - - 368
      - 151
- - - - 370
      - 151
  - - - 370
      - 222
  - - - 380
      - 222
  - - - 380
      - 199
  - - - 376
      - 199
  - - - 375
      - 198
  - - - 375
      - 151
- - - - 377
      - 152
  - - - 377
      - 197
  - - - 382
      - 197
  - - - 383
      - 196
  - - - 383
      - 152
- - - - 385
      - 151
  - - - 385
      - 197
  - - - 383
      - 199
  - - - 382
      - 199
  - - - 382
      - 222
  - - - 392
      - 222
  - - - 392
      - 199
  - - - 391
      - 199
  - - - 390
      - 198
  - - - 390
      - 151
- - - - 392
      - 152
  - - - 392
      - 197
  - - - 397
      - 197
  - - - 397
      - 193
  - - - 398
      - 192
  - - - 398
      - 171
  - - - 397
      - 170
  - - - 397
      - 152
- - - - 399
      - 151
  - - - 399
      - 169
  - - - 400
      - 170
  - - - 400
      - 193
  - - - 399
      - 194
  - - - 399
      - 198
  - - - 398
      - 199
  - - - 394
      - 199
  - - - 394
      - 222
  - - - 404
      - 222
  - - - 404
      - 151
- - - - 407
      - 151
  - - - 407
      - 222
  - - - 417
      - 222
  - - - 417
      - 199
  - - - 412
      - 199
  - - - 411
      - 198
  - - - 411
      - 151
- - - - 413
      - 152
  - - - 413
      - 197
  - - - 419
      - 197
  - - - 419
      - 152
- - - - 421
      - 151
  - - - 421
      - 198
  - - - 420
      - 199
  - - - 419
      - 199
  - - - 419
      - 222
  - - - 429
      - 222
  - - - 429
      - 199
  - - - 427
      - 199
  - - - 425
      - 197
  - - - 425
      - 151
- - - - 427
      - 152
  - - - 427
      - 196
  - - - 428
      - 197
  - - - 433
      - 197
  - - - 433
      - 193
  - - - 434
      - 192
  - - - 434
      - 182
  - - - 433
      - 181
  - - - 433
      - 152
- - - - 435
      - 151
  - - - 435
      - 180
  - - - 436
      - 181
  - - - 436
      - 193
  - - - 435
      - 194
  - - - 435
      - 198
  - - - 434
      - 199
  - - - 431
      - 199
  - - - 431
      - 222
  - - - 441
      - 222
  - - - 441
      - 199
  - - - 440
      - 198
  - - - 440
      - 151
- - - - 442
      - 152
  - - - 442
      - 197
  - - - 447
      - 197
  - - - 447
      - 193
  - - - 448
      - 192
  - - - 448
      - 172
  - - - 447
      - 171
  - - - 447
      - 152
- - - - 449
      - 151
  - - - 449
      - 170
  - - - 450
      - 171
  - - - 450
      - 193
  - - - 449
      - 194
  - - - 449
      - 198
  - - - 448
      - 199
  - - - 444
      - 199
  - - - 444
      - 222
  - - - 454
      - 222
  - - - 454
      - 151
- - - - 456
      - 151
  - - - 456
      - 222
  - - - 466
      - 222
  - - - 466
      - 199
  - - - 462
      - 199
  - - - 461
      - 198
  - - - 461
      - 151
- - - - 463
      - 152
  - - - 463
      - 197
  - - - 469
      - 197
  - - - 469
      - 152
- - - - 471
      - 151
  - - - 471
      - 198
  - - - 470
      - 199
  - - - 468
      - 199
  - - - 468
      - 222
  - - - 478
      - 222
  - - - 478
      - 199
  - - - 477
      - 199
  - - - 476
      - 198
  - - - 476
      - 151
- - - - 478
      - 152
  - - - 478
      - 197
  - - - 483
      - 197
  - - - 483
      - 194
  - - - 484
      - 193
  - - - 484
      - 155
  - - - 483
      - 154
  - - - 483
      - 152
- - - - 485
      - 151
  - - - 485
      - 153
  - - - 486
      - 154
  - - - 486
      - 194
  - - - 485
      - 195
  - - - 485
      - 198
  - - - 484
      - 199
  - - - 481
      - 199
  - - - 480
      - 200
  - - - 480
      - 222
  - - - 491
      - 222
  - - - 491
      - 151
- - - - 493
      - 151
  - - - 493
      - 222
  - - - 503
      - 222
  - - - 503
      - 199
  - - - 499
      - 199
  - - - 497
      - 197
  - - - 497
      - 151
- - - - 499
      - 152
  - - - 499
      - 196
  - - - 500
      - 197
  - - - 505
      - 197
  - - - 505
      - 193
  - - - 506
      - 192
  - - - 506
      - 182
  - - - 505
      - 181
  - - - 505
      - 152
- - - - 507
      - 151
  - - - 507
      - 180
  - - - 508
      - 181
  - - - 508
      - 193
  - - - 507
      - 194
  - - - 507
      - 198
  - - - 506
      - 199
  - - - 505
      - 199
  - - - 505
      - 222
  - - - 515
      - 222
  - - - 515
      - 199
  - - - 513
      - 199
  - - - 512
      - 198
  - - - 512
      - 151
- - - - 514
      - 152
  - - - 514
      - 197
  - - - 519
      - 197
  - - - 519
      - 193
  - - - 520
      - 192
  - - - 520
      - 172
  - - - 519
      - 171
  - - - 519
      - 152
- - - - 521
      - 151
  - - - 521
      - 170
  - - - 522
      - 171
  - - - 522
      - 193
  - - - 521
      - 194
  - - - 521
      - 198
  - - - 520
      - 199
  - - - 517
      - 199
  - - - 517
      - 222
  - - - 528
      - 222
  - - - 528
      - 199
  - - - 527
      - 199
  - - - 526
      - 198
  - - - 526
      - 151
- - - - 528
      - 152
  - - - 528
      - 197
  - - - 533
      - 197
  - - - 533
      - 195
  - - - 534
      - 194
  - - - 534
      - 152
- - - - 536
      - 151
  - - - 536
      - 195
  - - - 535
      - 196
  - - - 535
      - 198
  - - - 534
      - 199
  - - - 530
      - 199
  - - - 530
      - 222
  - - - 540
      - 222
  - - - 540
      - 151
- - - - 542
      - 151
  - - - 542
      - 222
  - - - 552
      - 222
  - - - 552
      - 199
  - - - 549
      - 199
  - - - 547
      - 197
  - - - 547
      - 151
- - - - 549
      - 152
  - - - 549
      - 196
  - - - 550
      - 197
  - - - 555
      - 197
  - - - 555
      - 193
  - - - 556
      - 192
  - - - 556
      - 185
  - - - 555
      - 184
  - - - 555
      - 152
- - - - 557
      - 151
  - - - 557
      - 183
  - - - 558
      - 184
  - - - 558
      - 193
  - - - 557
      - 194
  - - - 557
      - 198
  - - - 556
      - 199
  - - - 554
      - 199
  - - - 554
      - 222
  - - - 565
      - 222
  - - - 565
      - 200
  - - - 564
      - 199
  - - - 563
      - 199
  - - - 562
      - 198
  - - - 562
      - 151
- - - - 564
      - 152
  - - - 564
      - 197
  - - - 569
      - 197
  - - - 569
      - 195
  - - - 570
      - 194
  - - - 570
      - 152
- - - - 572
      - 151
  - - - 572
      - 195
  - - - 571
      - 196
  - - - 571
      - 198
  - - - 570
      - 199
  - - - 567
      - 199
  - - - 567
      - 222
  - - - 577
      - 222
  - - - 577
      - 151
- - - - 579
      - 151
  - - - 579
      - 222
  - - - 589
      - 222
  - - - 589
      - 199
  - - - 585
      - 199
  - - - 584
      - 198
  - - - 584
      - 151
- - - - 586
      - 152
  - - - 586
      - 197
  - - - 591
      - 197
  - - - 591
      - 193
  - - - 592
      - 192
  - - - 592
      - 172
  - - - 591
      - 171
  - - - 591
      - 152
- - - - 593
      - 151
  - - - 593
      - 170
  - - - 594
      - 171
  - - - 594
      - 193
  - - - 593
      - 194
  - - - 593
      - 198
  - - - 592
      - 199
  - - - 591
      - 199
  - - - 591
      - 222
  - - - 601
      - 222
  - - - 601
      - 199
  - - - 599
      - 199
  - - - 598
      - 198
  - - - 598
      - 151
- - - - 600
      - 152
  - - - 600
      - 197
  - - - 605
      - 197
  - - - 605
      - 194
  - - - 606
      - 193
  - - - 606
      - 152
- - - - 608
      - 151
  - - - 608
      - 194
  - - - 607
      - 195
  - - - 607
      - 198
  - - - 606
      - 199
  - - - 604
      - 199
  - - - 604
      - 222
  - - - 614
      - 222
  - - - 614
      - 199
  - - - 613
      - 199
  - - - 612
      - 198
  - - - 612
      - 151
- - - - 614
      - 152
  - - - 614
      - 197
  - - - 619
      - 197
  - - - 619
      - 196
  - - - 620
      - 195
  - - - 620
      - 152
- - - - 622
      - 151
  - - - 622
      - 196
  - - - 621
      - 197
  - - - 621
      - 198
  - - - 620
      - 199
  - - - 616
      - 199
  - - - 616
      - 222
  - - - 626
      - 222
  - - - 626
      - 151
- - - - 628
      - 151
  - - - 628
      - 222
  - - - 638
      - 222
  - - - 638
      - 151
midi_start_note: 7
video_file: /Users/erikvanraalte/dev/piano_tutorial_to_midi/Downloads/Speech Bubbles
  - The Smile [Piano Cover].mp4
