on:
  pull_request:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release software for all major operating systems
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller main.py --onefile
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
        name: ${{ matrix.os }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  - uses: actions/download-artifact@v3
    with:
      path: dist
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false
    - run: find ./dist/ -type f -print0 | tr / _ | xargs -0 mv -t ./dist/
    - run: |
        set -x
        assets=()
        for asset in ./dist/*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}